import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Todo } from '../grpc/proto/v1/todo/Todo'

const Home: NextPage<{ todos: Todo[] }> = ({ todos }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TODO's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>TODO's</h1>
        <ul style={{ paddingLeft: 0 }} >
          {todos && todos.map((todo: Todo) => <li style={{ listStyle: "none", paddingBottom: '1em' }} key={todo.id}><input type="checkbox" />&nbsp; {todo.title}</li>)}
        </ul>
      </main>
    </div >
  )
}

Home.getInitialProps = async () => {
  const response = await fetch(`http://localhost:3000/api/todos`);
  const data: { todos: Todo[] } = await response.json()
  return { todos: data.todos }
}

export default Home
